package com.azu.timetable.ui.theme

import androidx.compose.ui.graphics.Color

// Elegant Dark Palette (Design Theme)
val ElegantDark_Background = Color(0xFF1C1B1F)
val ElegantDark_Surface = Color(0xFF1C1B1F)
val ElegantDark_SurfaceCard = Color(0xFF2B2930)
val ElegantDark_SurfaceVariant = Color(0xFF2B2930)
val ElegantDark_Outline = Color(0xFF49454F)
val ElegantDark_OutlineVariant = Color(0xFF938F99)

val ElegantDark_Primary = Color(0xFFD0BCFF)
val ElegantDark_OnPrimary = Color(0xFF381E72)
val ElegantDark_PrimaryContainer = Color(0xFF4F378B)
val ElegantDark_OnPrimaryContainer = Color(0xFFEADDFF)

val ElegantDark_Secondary = Color(0xFFCCC2DC)
val ElegantDark_OnSecondary = Color(0xFF332D41)
val ElegantDark_SecondaryContainer = Color(0xFF4A4458)
val ElegantDark_OnSecondaryContainer = Color(0xFFE8DEF8)

val ElegantDark_TextPrimary = Color(0xFFE6E1E5)
val ElegantDark_TextSecondary = Color(0xFFCAC4D0)
val ElegantDark_TextMuted = Color(0xFF938F99)

// Material 3 Light Palette
val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF21005D)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_light_tertiary = Color(0xFF7D5260)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEF7FF)
val md_theme_light_onBackground = Color(0xFF1D1B20)
val md_theme_light_surface = Color(0xFFFEF7FF)
val md_theme_light_onSurface = Color(0xFF1D1B20)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

// Elegant Dark Palette (Material 3 Dark) - Deep, Rich, Sleek Dark
val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF3E2D69)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFCCC2DC)
val md_theme_dark_onSecondary = Color(0xFF332D41)
val md_theme_dark_secondaryContainer = Color(0xFF373342)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF492532)
val md_theme_dark_tertiaryContainer = Color(0xFF4D2B37)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF5E1B18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF0F0E13)
val md_theme_dark_onBackground = Color(0xFFF1EEF7)
val md_theme_dark_surface = Color(0xFF131218)
val md_theme_dark_onSurface = Color(0xFFF1EEF7)
val md_theme_dark_surfaceVariant = Color(0xFF1E1C24)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC8D6)
val md_theme_dark_outline = Color(0xFF383442)
val md_theme_dark_inverseOnSurface = Color(0xFF131218)
val md_theme_dark_inverseSurface = Color(0xFFF1EEF7)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(0xFF282531)
val md_theme_dark_scrim = Color(0xFF000000)

// Semantic accent colors for Timetable Slot categories in Elegant Dark
val BreakColorLight = Color(0xFFFFF3E0)
val BreakOnColorLight = Color(0xFFE65100)
val BreakColorDark = Color(0xFF2B2930)
val BreakOnColorDark = Color(0xFFCAC4D0)

val LabColorLight = Color(0xFFE8F5E9)
val LabOnColorLight = Color(0xFF2E7D32)
val LabColorDark = Color(0xFF283530)
val LabOnColorDark = Color(0xFFA5D6A7)

val ActivityColorLight = Color(0xFFEDE7F6)
val ActivityOnColorLight = Color(0xFF5E35B1)
val ActivityColorDark = Color(0xFF38284A)
val ActivityOnColorDark = Color(0xFFD0BCFF)

val MentoringColorLight = Color(0xFFE0F7FA)
val MentoringOnColorLight = Color(0xFF00838F)
val MentoringColorDark = Color(0xFF20353A)
val MentoringOnColorDark = Color(0xFF80DEEA)
